# Copyright (C) 2012, Parrot Foundation

=pod

=head1 NAME

README - Readme file for Parrot's 'parrot-docs4' documentation repository.

=head1 DESCRIPTION

The purpose of this README is to record the fact that this repository contains 
or will contain all of the documentation for version 4.0.0 through version 
4.11.0 of Parrot.

=head1 COPYRIGHT

Copyright (C) 2001-2012, Parrot Foundation.

=cut
